[package]
org = "your_org"
name = "user_crud_service"
version = "0.1.0"
distribution = "2201.9.0"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.28"
path = "lib/mysql-connector-java-8.0.28.jar"
